// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYzQFOmhkRIsXwGmhrFJoj76-mxCFZe4',
    appId: '1:942508006570:web:c8c74fa8e641f2b34384d3',
    messagingSenderId: '942508006570',
    projectId: 'quickfood-25988',
    authDomain: 'quickfood-25988.firebaseapp.com',
    storageBucket: 'quickfood-25988.appspot.com',
    measurementId: 'G-WKXCZQDWM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkb_sUG0PT_mnMxk4g7mHzd_Oe1mtWEtw',
    appId: '1:942508006570:android:319cb25ac0deefdd4384d3',
    messagingSenderId: '942508006570',
    projectId: 'quickfood-25988',
    storageBucket: 'quickfood-25988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCShN13vABOAlagpIvUQ50tssNxKcINM5U',
    appId: '1:942508006570:ios:c847068d789211534384d3',
    messagingSenderId: '942508006570',
    projectId: 'quickfood-25988',
    storageBucket: 'quickfood-25988.appspot.com',
    iosClientId: '942508006570-q0oc9ng1vb2dghvnrg2235a6jjdhr3v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );
}

